name: CI-CD Pipeline Carnivale Front

on:
  push:
    branches:
      - main
      - 'refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          npm run build
          ls -l ./build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: npm install


      - name: Run Tests
        run:
          npm test



# TODO: Doesn't work with githib pages
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: production-files
#          path: ./build
#
#      - name: Copy files to docs
#        run: |
#          cp -r ./build/* .
#          ls -l ./
#
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.SECRET_FOR_CARNIVALE_FRONT }}
#          publish_dir: .
